### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Chris-Gett** [thanks-to-it/popup-notices-for-woocommerce#3]
after update from 1.2.7 to 1.2.8 the plugin could not be reactivated

following error occurs:
Warning: include(/www/htdocs/***/wp-content/plugins/popup-notices-for-woocommerce/vendor/composer/../../src/classes/class-core.php): failed to open stream: No such file or directory in /www/htdocs/***/wp-content/plugins/sitepress-multilingual-cms/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/www/htdocs/***/wp-content/plugins/popup-notices-for-woocommerce/vendor/composer/../../src/classes/class-core.php' for inclusion (include_path='.:/usr/share/php:..') in /www/htdocs/***/wp-content/plugins/sitepress-multilingual-cms/vendor/composer/ClassLoader.php on line 444

Fatal error: Uncaught Error: Class 'ThanksToIT\PNWC\Core' not found in /www/htdocs/***/wp-content/plugins/popup-notices-for-woocommerce/popup-notices-for-woocommerce.php:32 

Stack trace: #0 /www/htdocs/***/wp-admin/includes/plugin.php(2300): 
include() #1 /www/htdocs/***/wp-admin/plugins.php(191): plugin_sandbox_scrape('woocommerce/woo...') #2 {main} thrown in /www/htdocs/***/wp-content/plugins/popup-notices-for-woocommerce/popup-notices-for-woocommerce.php on line 32 

It seems the plugin have a conflict with WPML Plugin?

Wordpress V: 5.7.2
PHP:  7.4

**Comment by pablo-sg-pacheco** [comment]
Hi @Chris-Gett ,
I just updated to version 1.2.9.

Let me know if it helps

**Comment by Chris-Gett** [comment]
Hi Pablo, the patch is working fine for me. 
Good Job, thank you!

**Comment by pablo-sg-pacheco** [comment]
Great then, thanks :)
