### ISSUE TITLE
woocommerce hpos compatibility

### ISSUE THREAD

**Issue by jessebrightman** [thanks-to-it/popup-notices-for-woocommerce#6]
Hello,

As woocommerce is rolling out the hpos system for order storage, it would be great to add the compatibility check so that this plugin will work going forward.  I will have a look and see what is required.

**Comment by pablo-sg-pacheco** [comment]
Hi @jessebrightman ,

Sorry for the long delay, but finally I added the compatibility. I'm closing the ticket
